version: '3.8'

services: 
  localstack:
    image: localstack/localstack:1.4.0
    container_name: localstack
    environment: 
      - SERVICES=cloudformation,apigateway,lambda
      - AWS_DEFAULT_REGION=us-east-1
      - EAGER_SERVICE_LOADING=1
      - EDGE_PORT=4566
    ports: 
      - "4566-4583:4566-4583"
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"